In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error
from sklearn.preprocessing import PolynomialFeatures

In [28]:
df=pd.read_csv('manufacturing.csv')
df

,Temperature (°C),Pressure (kPa),Temperature x Pressure,Material Fusion Metric,Material Transformation Metric,Quality Rating
0,209.762701,8.050855,1688.769167,44522.217074,9.229576e+06,99.999971
1,243.037873,15.812068,3842.931469,63020.764997,1.435537e+07,99.985703
2,220.552675,7.843130,1729.823314,49125.950249,1.072839e+07,99.999758
3,208.976637,23.786089,4970.736918,57128.881547,9.125702e+06,99.999975
4,184.730960,15.797812,2918.345014,38068.201283,6.303792e+06,100.000000
...,...,...,...,...,...,...
3952,156.811578,21.794290,3417.596965,34941.963896,3.855501e+06,100.000000
3953,197.850406,8.291704,1640.516924,39714.857236,7.744742e+06,99.999997
3954,241.357144,16.391910,3956.304672,62657.690952,1.405957e+07,99.989318
3955,209.040239,23.809936,4977.234763,57195.985528,9.134036e+06,99.999975
3956,163.359996,24.332133,3974.897121,41092.392901,4.358913e+06,100.000000

In [29]:
df.corr()

,Temperature (°C),Pressure (kPa),Temperature x Pressure,Material Fusion Metric,Material Transformation Metric,Quality Rating
Temperature (°C),1.000000,-0.024754,0.571743,0.974901,0.971210,-0.461279
Pressure (kPa),-0.024754,1.000000,0.773572,0.151095,-0.022862,0.013129
Temperature x Pressure,0.571743,0.773572,1.000000,0.694733,0.555579,-0.258474
Material Fusion Metric,0.974901,0.151095,0.694733,1.000000,0.976708,-0.511972
Material Transformation Metric,0.971210,-0.022862,0.555579,0.976708,1.000000,-0.575756
Quality Rating,-0.461279,0.013129,-0.258474,-0.511972,-0.575756,1.000000

In [30]:
x=df.drop(columns='Quality Rating')
y=df['Quality Rating']

In [31]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)
xtrain

,Temperature (°C),Pressure (kPa),Temperature x Pressure,Material Fusion Metric,Material Transformation Metric
2533,216.199164,9.621265,2080.109475,47632.706816,1.010551e+07
1613,178.624483,12.048327,2152.126171,33655.667371,5.699174e+06
3347,159.225345,16.660873,2652.833232,29977.513751,4.036517e+06
1117,107.032012,22.092997,2364.657879,22239.454281,1.225655e+06
3591,125.084376,13.242953,1656.486513,17968.594689,1.956907e+06
...,...,...,...,...,...
1130,100.412927,20.827861,2091.386466,19117.877447,1.012005e+06
1294,104.953812,14.896303,1563.423745,14320.789657,1.155876e+06
860,287.423408,10.143206,2915.394894,83655.795723,2.374458e+07
3507,142.741438,20.320083,2900.517791,28765.396998,2.907961e+06
3174,195.308068,23.402574,4570.711591,50962.374819,7.449526e+06

In [32]:
xtest

,Temperature (°C),Pressure (kPa),Temperature x Pressure,Material Fusion Metric,Material Transformation Metric
149,299.769401,17.080988,5120.357689,94845.246019,2.693749e+07
1025,269.669054,9.618072,2593.696257,73611.140498,1.961062e+07
2153,276.213323,11.994665,3313.086346,78019.495966,2.107322e+07
720,250.204330,12.383619,3098.435063,64501.284332,1.566319e+07
325,191.228113,14.653398,2802.141637,39714.599277,6.992652e+06
...,...,...,...,...,...
1226,191.642452,21.890891,4195.224017,47217.187469,7.037940e+06
736,155.468054,6.962775,1082.489093,24507.872880,3.757664e+06
3782,222.066921,16.061066,3566.631571,53456.795467,1.095069e+07
927,107.711449,22.760477,2451.563967,23392.578236,1.249124e+06
3775,141.644842,18.739819,2654.398725,26644.326400,2.841506e+06

In [33]:
ytrain

2533     99.999895
1613    100.000000
3347    100.000000
1117    100.000000
3591    100.000000
           ...
1130    100.000000
1294    100.000000
860      83.596543
3507    100.000000
3174     99.999999
Name: Quality Rating, Length: 3165, dtype: float64

In [34]:
poly=PolynomialFeatures(degree=7)
updated_xtrain=poly.fit_transform(xtrain)
updated_xtest=poly.transform(xtest)

In [35]:
updated_xtrain

array([[1.00000000e+00, 2.16199164e+02, 9.62126513e+00, ...,
        2.39111673e+44, 5.07286807e+46, 1.07623313e+49],
       [1.00000000e+00, 1.78624483e+02, 1.20483269e+01, ...,
        6.81045110e+42, 1.15326620e+45, 1.95291460e+47],
       [1.00000000e+00, 1.59225345e+02, 1.66608728e+01, ...,
        9.62996915e+41, 1.29668958e+44, 1.74601168e+46],
       ...,
       [1.00000000e+00, 2.87423408e+02, 1.01432062e+01, ...,
        5.28219813e+46, 1.49928148e+49, 4.25551049e+51],
       [1.00000000e+00, 1.42741438e+02, 2.03200825e+01, ...,
        1.72061392e+41, 1.73940854e+43, 1.75840845e+45],
       [1.00000000e+00, 1.95308068e+02, 2.34025744e+01, ...,
        5.95857541e+43, 8.71006523e+45, 1.27321098e+48]],
      shape=(3165, 792))

In [36]:
poly_model=LinearRegression()

In [37]:
poly_model.fit(updated_xtrain,ytrain)

LinearRegression()

In [ ]:
#model evaluation

ytrain_pred = poly_model.predict(updated_xtrain)
train_score = r2_score(ytrain, ytrain_pred)
print(f'Train Score: {train_score}')

ytest_pred = poly_model.predict(updated_xtest)
test_score = r2_score(ytest, ytest_pred)
print(f'Test Score: {test_score}')

Train Score: 0.9517548482942992
Test Score: 0.9518602102515942

In [39]:
mean_absolute_error(ytest,ytest_pred)

1.1508286490008601

In [40]:
root_mean_squared_error(ytest,ytest_pred)

3.1349270017726663


The model is good fit