In [11]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [12]:
import seaborn as sns

In [13]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,root_mean_squared_error

In [14]:
df=pd.read_csv(r'C:\Users\ayyok\OneDrive\Desktop\PYspider\MachineLearning\Student_Performance1.csv')

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  str
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), str(1)
memory usage: 493.2 KB

In [16]:
df['Extracurricular Activities']=df['Extracurricular Activities'].map({'Yes':1,'No':0})

In [17]:
df.corr(numeric_only=True)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.012390,0.003873,0.001245,0.017463,0.373730
Previous Scores,-0.012390,1.000000,0.008369,0.005944,0.007888,0.915189
Extracurricular Activities,0.003873,0.008369,1.000000,-0.023284,0.013103,0.024525
Sleep Hours,0.001245,0.005944,-0.023284,1.000000,0.003990,0.048106
Sample Question Papers Practiced,0.017463,0.007888,0.013103,0.003990,1.000000,0.043268
Performance Index,0.373730,0.915189,0.024525,0.048106,0.043268,1.000000

In [18]:
x=df.drop(columns='Performance Index')# (OR)x=df[['Hours Studied','Previous Scores','Extracurricular Activities','Sleep Hours','Sample Question Papers Practiced']]
y=df['Performance Index']

In [19]:
print(x)
print(y)

      Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9
1                 4               82                           0            4
2                 8               51                           1            7
3                 5               52                           1            5
4                 7               75                           0            8
...             ...              ...                         ...          ...
9995              1               49                           1            4
9996              7               64                           1            8
9997              6               83                           1            8
9998              9               97                           1            7
9999              7               74                           0            8

      Sample Question Papers Practiced
0                                    1
1                                    2
2                                    2
3                                    2
4                                    5
...                                ...
9995                                 2
9996                                 5
9997                                 5
9998                                 0
9999                                 1

[10000 rows x 5 columns]
0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

Check data is linear or non-linear

In [20]:
df.corr(numeric_only=True)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.012390,0.003873,0.001245,0.017463,0.373730
Previous Scores,-0.012390,1.000000,0.008369,0.005944,0.007888,0.915189
Extracurricular Activities,0.003873,0.008369,1.000000,-0.023284,0.013103,0.024525
Sleep Hours,0.001245,0.005944,-0.023284,1.000000,0.003990,0.048106
Sample Question Papers Practiced,0.017463,0.007888,0.013103,0.003990,1.000000,0.043268
Performance Index,0.373730,0.915189,0.024525,0.048106,0.043268,1.000000

In [21]:
df.cov(numeric_only=True)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,6.704520,-0.556391,0.005014,0.005468,0.129654,18.592055
Previous Scores,-0.556391,300.784930,0.072575,0.174829,0.392262,304.946801
Extracurricular Activities,0.005014,0.072575,0.249998,-0.019743,0.018785,0.235593
Sleep Hours,0.005468,0.174829,-0.019743,2.875951,0.019403,1.567378
Sample Question Papers Practiced,0.129654,0.392262,0.018785,0.019403,8.221683,2.383613
Performance Index,18.592055,304.946801,0.235593,1.567378,2.383613,369.122377

In [22]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

# train-test-split

**Syntax**

xtrain,xtest,ytrain,ytest=train_test_split(

    x,

    y,

    train_size=0.8,

    random_state=42
)

In [23]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)#train_size=0.8 to split the data for train and test
#Explain random test?(Interviwe question)

In [24]:
xtrain

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
9254,5,49,0,7,5
1561,2,48,1,7,6
1670,2,81,0,7,2
6087,2,46,0,6,1
6669,8,47,0,9,0
...,...,...,...,...,...
5734,8,50,1,6,6
5191,4,68,0,9,3
5390,9,48,0,7,6
860,1,47,0,9,0
7270,2,46,0,6,6

In [25]:
model=LinearRegression()#Model creation

In [26]:
model.fit(xtrain,ytrain)#model training   #(model learns the pattern from xtrain(input) and ytrain(output)
#pattern? mx+c(straight line))

LinearRegression()

In [27]:
ytrain

9254    36.0
1561    25.0
1670    59.0
6087    22.0
6669    40.0
        ...
5734    48.0
5191    51.0
5390    44.0
860     20.0
7270    24.0
Name: Performance Index, Length: 8000, dtype: float64

In [28]:
model.intercept_   #Intercept value  #Attribute

np.float64(-33.921946215556126)

Intercept conclusion 

Base or initial value of 'performance index' is -33.921946215556126 when all features are equal to zero

In [29]:
model.coef_ # used to find slope value.

array([2.85248393, 1.0169882 , 0.60861668, 0.47694148, 0.19183144])

**Conclusion for slope**

The rate of change of Performance Index is 2.85248393 with respect to Hours Studied by 1 unit.


The rate of change of Performance Index is 1.0169882  with respect to Previous Score by 1 unit.


The rate of change of Performance Index is 0.60861668 with respect to Extracurricular Activities by 1 unit.


The rate of change of Performance Index is 0.47694148 with respect to Sleep Hours by 1 unit.


The rate of change of Performance Index is 0.19183144 with respect to Sample Question Papers Practiced by 1 unit.

# Model evaluation

**Train data**

In [30]:
#error=actual output-predicted output

In [31]:
#ytrain(actual)
#ytrain_predicted(predicted_values)
''' 
syntax
model.predict(x)
ytrain_predicted=model.predict(xtrain)
ytest_predicted=model.predict(xtest)
'''
ytrain_predicted=model.predict(xtrain)

sntax for metrics

metricname(actualoutput,predicted output)

In [32]:
r2_score(ytrain,ytrain_predicted)

0.9886898790682355

**Conclusion**

The model learns the pattern well(strong) bcuz previous scorre and target column corelated strongly

In [33]:
ytest_predicted=model.predict(xtest)

In [34]:
r2_score(ytest,ytest_predicted)

0.9889832909573145

In [35]:
mean_absolute_error(ytest,ytest_predicted)

1.6111213463123044

In [36]:
root_mean_squared_error(ytrain,ytrain_predicted)

2.0419931071198567