In [1]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import classification_report

In [2]:
df=pd.read_csv('loan_data.csv')
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [3]:
x=df.drop(columns='loan_status')
y=df['loan_status']

In [4]:
num_cols=x.select_dtypes(include='number').columns
x=x[num_cols]

In [5]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [6]:
grid_search=GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid={
        'criterion':['gini','entropy'],
        'splitter':['best','random'],
        'max_depth':[None,5,10,20],
        'min_samples_split':[2,3,5,7],
        'min_samples_leaf':[1,3,5,7],
        'max_features':['auto','sqrt','log2'] 
    },
    cv=5,
    verbose=0
)
grid_search.fit(xtrain,ytrain)

c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
1280 fits failed out of a total of 3840.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1280 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
  File "c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.81288889 0.78891667 0.80916667 0.80180556
 0.81633333 0.80738889 0.82497222 0.81202778 0.82280556 0.8035
 0.82280556 0.8035     0.82280556 0.8035     0.82597222 0.80705556
 0.82958333 0.78858333 0.82958333 0.78858333 0.82958333 0.78858333
 0.82958333 0.78858333 0.83816667 0.79044444 0.83816667 0.79044444
 0.83816667 0.79044444 0.83816667 0.79044444 0.81302778 0.79394444
 0.81430556 0.80847222 0.81933333 0.81355556 0.82036111 0.81911111
 0.82727778 0.82205556 0.82727778 0.82205556 0.82727778 0.82205556
 0.82677778 0.82716667 0.83211111 0.83030556 0.83211111 0.83030556
 0.83211111 0.83030556 0.83211111 0.83030556 0.83836111 0.829
 0.83836111 0.829      0.83836111 0.829      0.83836111 0.829
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.83483333 0.78641667 0.83480556 0.78641667
 0.83572222 0.78641667 0.83572222 0.78641667 0.83533333 0.78583333
 0.83533333 0.78583333 0.83533333 0.78583333 0.83533333 0.78583333
 0.83616667 0.78494444 0.83616667 0.78494444 0.83616667 0.78494444
 0.83616667 0.78494444 0.83630556 0.78494444 0.83630556 0.78494444
 0.83630556 0.78494444 0.83630556 0.78494444 0.8405     0.79361111
 0.8405     0.79361111 0.8405     0.79361111 0.84491667 0.79611111
 0.84052778 0.79352778 0.84052778 0.79352778 0.84052778 0.79352778
 0.84494444 0.79597222 0.85197222 0.79708333 0.85197222 0.79708333
 0.85197222 0.79708333 0.85197222 0.79708333 0.85341667 0.79441667
 0.85341667 0.79441667 0.85341667 0.79441667 0.85341667 0.79441667
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.85280556 0.80327778 0.85213889 0.80802778
 0.84983333 0.80661111 0.85147222 0.80630556 0.85069444 0.80427778
 0.85069444 0.80427778 0.85069444 0.80427778 0.84927778 0.79836111
 0.85236111 0.78813889 0.85236111 0.78813889 0.85236111 0.78813889
 0.85236111 0.78813889 0.85061111 0.78766667 0.85061111 0.78766667
 0.85061111 0.78766667 0.85061111 0.78766667 0.85386111 0.81508333
 0.85380556 0.81452778 0.85422222 0.81377778 0.85277778 0.81611111
 0.85261111 0.81583333 0.85261111 0.81583333 0.85261111 0.81583333
 0.85325    0.815      0.85375    0.81344444 0.85375    0.81344444
 0.85375    0.81344444 0.85375    0.81344444 0.85355556 0.81322222
 0.85355556 0.81322222 0.85355556 0.81322222 0.85355556 0.81322222
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.82530556 0.8205     0.82597222 0.81777778
 0.82575    0.82108333 0.83       0.82375    0.829      0.80866667
 0.829      0.80866667 0.829      0.80866667 0.82888889 0.80625
 0.83541667 0.78936111 0.83541667 0.78936111 0.83541667 0.78936111
 0.83541667 0.78936111 0.83827778 0.78988889 0.83827778 0.78988889
 0.83827778 0.78988889 0.83827778 0.78988889 0.82641667 0.82466667
 0.82805556 0.82663889 0.82719444 0.82788889 0.82841667 0.82955556
 0.83061111 0.83347222 0.83061111 0.83347222 0.83061111 0.83347222
 0.83433333 0.83530556 0.83441667 0.83591667 0.83441667 0.83591667
 0.83441667 0.83591667 0.83441667 0.83591667 0.84202778 0.82244444
 0.84202778 0.82244444 0.84202778 0.82244444 0.84202778 0.82244444
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.81186111 0.78986111 0.81680556 0.79872222
 0.81711111 0.80605556 0.82141667 0.81122222 0.82366667 0.80402778
 0.82366667 0.80402778 0.82366667 0.80402778 0.82230556 0.80530556
 0.83083333 0.78908333 0.83083333 0.78908333 0.83083333 0.78908333
 0.83083333 0.78908333 0.83769444 0.78869444 0.83769444 0.78869444
 0.83769444 0.78869444 0.83769444 0.78869444 0.817      0.79883333
 0.81763889 0.80561111 0.81930556 0.81241667 0.81961111 0.81822222
 0.82066667 0.82441667 0.82066667 0.82441667 0.82066667 0.82441667
 0.82213889 0.82075    0.83180556 0.83397222 0.83180556 0.83397222
 0.83180556 0.83397222 0.83180556 0.83397222 0.83772222 0.83261111
 0.83772222 0.83261111 0.83772222 0.83261111 0.83772222 0.83261111
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.83461111 0.78641667 0.83461111 0.78641667
 0.83461111 0.78641667 0.83461111 0.78641667 0.83411111 0.78583333
 0.83411111 0.78583333 0.83411111 0.78583333 0.83411111 0.78583333
 0.83463889 0.78494444 0.83463889 0.78494444 0.83463889 0.78494444
 0.83463889 0.78494444 0.83483333 0.78494444 0.83483333 0.78494444
 0.83483333 0.78494444 0.83483333 0.78494444 0.84061111 0.79358333
 0.84061111 0.79358333 0.84061111 0.79358333 0.84061111 0.79627778
 0.84058333 0.79352778 0.84058333 0.79352778 0.84058333 0.79352778
 0.84058333 0.79616667 0.84077778 0.79708333 0.84077778 0.79708333
 0.84077778 0.79708333 0.84077778 0.79708333 0.84072222 0.79441667
 0.84072222 0.79441667 0.84072222 0.79441667 0.84072222 0.79441667
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.84891667 0.80672222 0.84947222 0.80747222
 0.85077778 0.80622222 0.84866667 0.80533333 0.849      0.80419444
 0.849      0.80419444 0.849      0.80419444 0.84880556 0.79766667
 0.84711111 0.78819444 0.84711111 0.78819444 0.84711111 0.78819444
 0.84711111 0.78819444 0.84913889 0.78763889 0.84913889 0.78763889
 0.84913889 0.78763889 0.84913889 0.78763889 0.85261111 0.81122222
 0.85269444 0.80666667 0.85311111 0.82       0.85258333 0.81663889
 0.85488889 0.80772222 0.85488889 0.80772222 0.85488889 0.80772222
 0.85330556 0.818      0.853      0.82261111 0.853      0.82261111
 0.853      0.82261111 0.853      0.82261111 0.85430556 0.81972222
 0.85430556 0.81972222 0.85430556 0.81972222 0.85430556 0.81972222
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.82813889 0.81666667 0.82827778 0.81433333
 0.82969444 0.81808333 0.83033333 0.81994444 0.82922222 0.80833333
 0.82922222 0.80833333 0.82922222 0.80833333 0.83094444 0.80938889
 0.83458333 0.79002778 0.83458333 0.79002778 0.83458333 0.79002778
 0.83458333 0.79002778 0.83755556 0.78952778 0.83755556 0.78952778
 0.83755556 0.78952778 0.83755556 0.78952778 0.83116667 0.83141667
 0.82819444 0.82741667 0.83152778 0.83330556 0.83163889 0.83438889
 0.83183333 0.83286111 0.83183333 0.83286111 0.83183333 0.83286111
 0.83288889 0.83663889 0.83363889 0.83661111 0.83363889 0.83661111
 0.83363889 0.83661111 0.83363889 0.83661111 0.83961111 0.83580556
 0.83961111 0.83580556 0.83961111 0.83580556 0.83961111 0.83580556]
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10, 20],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 3, 5, 7],
                         'min_samples_split': [2, 3, 5, 7],
                         'splitter': ['best', 'random']})

In [7]:
grid_search.best_params_  #to get best parameter

{'criterion': 'entropy',
 'max_depth': 10,
 'max_features': 'log2',
 'min_samples_leaf': 3,
 'min_samples_split': 2,
 'splitter': 'best'}

In [8]:
grid_search.best_estimator_

DecisionTreeClassifier(criterion='entropy', max_depth=10, max_features='log2',
                       min_samples_leaf=3, random_state=42)

In [9]:
model=grid_search.best_estimator_
model.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=10, max_features='log2',
                       min_samples_leaf=3, random_state=42)

In [10]:
ytrain_pred=model.predict(xtrain)
ytest_pred=model.predict(xtest)

In [11]:
print(classification_report(ytrain,ytrain_pred))
print(classification_report(ytest,ytest_pred))

              precision    recall  f1-score   support

           0       0.90      0.94      0.92     28010
           1       0.75      0.65      0.70      7990

    accuracy                           0.87     36000
   macro avg       0.83      0.79      0.81     36000
weighted avg       0.87      0.87      0.87     36000

              precision    recall  f1-score   support

           0       0.89      0.92      0.91      6990
           1       0.69      0.60      0.64      2010

    accuracy                           0.85      9000
   macro avg       0.79      0.76      0.77      9000
weighted avg       0.85      0.85      0.85      9000

In [12]:
result=pd.DataFrame(grid_search.cv_results_)
result

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004001,0.000910,0.000000,0.000000,gini,None,auto,1,2,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
1,0.002401,0.001021,0.000000,0.000000,gini,None,auto,1,2,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
2,0.002000,0.000633,0.000000,0.000000,gini,None,auto,1,3,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
3,0.002008,0.000632,0.000000,0.000000,gini,None,auto,1,3,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
4,0.001802,0.000749,0.000000,0.000000,gini,None,auto,1,5,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,0.018395,0.001356,0.003804,0.000401,entropy,20,log2,7,3,random,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.845556,0.842778,0.824861,0.841806,0.824028,0.835806,0.009361,146
764,0.077594,0.000972,0.004014,0.000023,entropy,20,log2,7,5,best,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.836111,0.845833,0.836111,0.844306,0.835694,0.839611,0.004485,101
765,0.018189,0.000734,0.003182,0.000413,entropy,20,log2,7,5,random,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.845556,0.842778,0.824861,0.841806,0.824028,0.835806,0.009361,146
766,0.075648,0.000921,0.003586,0.000464,entropy,20,log2,7,7,best,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.836111,0.845833,0.836111,0.844306,0.835694,0.839611,0.004485,101
767,0.018742,0.001108,0.003214,0.000346,entropy,20,log2,7,7,random,"{'criterion': 'entropy', 'max_depth': 20, 'max...",0.845556,0.842778,0.824861,0.841806,0.824028,0.835806,0.009361,146

In [13]:
result.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
648,0.067234,0.007017,0.003580,0.000817,entropy,10,log2,3,2,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.855139,0.864167,0.850278,0.853750,0.851111,0.854889,0.004959,1
652,0.056567,0.002311,0.002941,0.000196,entropy,10,log2,3,5,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.855139,0.864167,0.850278,0.853750,0.851111,0.854889,0.004959,1
650,0.060622,0.004081,0.003629,0.000484,entropy,10,log2,3,3,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.855139,0.864167,0.850278,0.853750,0.851111,0.854889,0.004959,1
664,0.055996,0.001660,0.003586,0.000477,entropy,10,log2,7,2,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.851944,0.857917,0.853472,0.858194,0.850000,0.854306,0.003255,4
670,0.062084,0.007532,0.003597,0.000796,entropy,10,log2,7,7,best,"{'criterion': 'entropy', 'max_depth': 10, 'max...",0.851944,0.857917,0.853472,0.858194,0.850000,0.854306,0.003255,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,0.004202,0.001164,0.000000,0.000000,gini,None,auto,5,3,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
18,0.004599,0.001856,0.000000,0.000000,gini,None,auto,5,3,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
17,0.001995,0.000628,0.000000,0.000000,gini,None,auto,5,2,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
16,0.002347,0.000598,0.000000,0.000000,gini,None,auto,5,2,best,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513
15,0.002179,0.000958,0.000000,0.000000,gini,None,auto,3,7,random,"{'criterion': 'gini', 'max_depth': None, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,513

In [14]:
model=DecisionTreeClassifier(
criterion= 'entropy',
 max_depth= 10,
 max_features= 'log2',
 min_samples_leaf= 3,
 min_samples_split= 2,
 splitter= 'best',
 random_state=42)

In [15]:
model.fit(xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', max_depth=10, max_features='log2',
                       min_samples_leaf=3, random_state=42)

In [ ]:
grid_search=GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid={
        'criterion':['gini','entropy'],
        'splitter':['best','random'],
        'max_depth':[None,5,10,20],
        'min_samples_split':[2,3,5,7],
        'min_samples_leaf':[1,3,5,7],
        'max_features':['sqrt','log2'] 
    },
    cv=3,
    verbose=1,
    error_score='raise', #to find which para value is makes the nan values
    n_jobs=1 #if u want to use all the cpu cores pass -1 as a parameter value and runs parallely
)
grid_search.fit(xtrain,ytrain)

Fitting 3 folds for each of 512 candidates, totalling 1536 fits

In [17]:
model1=grid_search.best_estimator_
model1.fit(xtrain,ytrain)

DecisionTreeClassifier(max_depth=10, max_features='log2', min_samples_split=5,
                       random_state=42)

In [27]:
result1=pd.DataFrame(grid_search.cv_results_)
result1.sort_values(by='rank_test_score')

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
164,0.040718,0.001853,0.003998,7.370010e-07,gini,10,log2,1,5,best,"{'criterion': 'gini', 'max_depth': 10, 'max_fe...",0.855000,0.855333,0.849583,0.853306,0.002636,1
166,0.040012,0.000862,0.003693,4.922159e-04,gini,10,log2,1,7,best,"{'criterion': 'gini', 'max_depth': 10, 'max_fe...",0.853583,0.853583,0.851750,0.852972,0.000864,2
162,0.039786,0.001684,0.003629,5.278569e-04,gini,10,log2,1,3,best,"{'criterion': 'gini', 'max_depth': 10, 'max_fe...",0.849750,0.855000,0.851750,0.852167,0.002163,3
114,0.023004,0.000005,0.003348,4.583457e-04,gini,5,log2,5,3,best,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.851333,0.854417,0.850667,0.852139,0.001633,4
118,0.022317,0.000445,0.003012,2.284869e-05,gini,5,log2,5,7,best,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.851333,0.854417,0.850667,0.852139,0.001633,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
333,0.006996,0.000009,0.003003,6.633961e-06,entropy,5,sqrt,3,5,random,"{'criterion': 'entropy', 'max_depth': 5, 'max_...",0.783083,0.785167,0.785250,0.784500,0.001002,504
75,0.007696,0.000930,0.003007,9.282974e-05,gini,5,sqrt,3,3,random,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.783083,0.785167,0.785250,0.784500,0.001002,504
77,0.006997,0.000820,0.003035,7.287892e-04,gini,5,sqrt,3,5,random,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.783083,0.785167,0.785250,0.784500,0.001002,504
73,0.007203,0.001130,0.003826,2.358169e-04,gini,5,sqrt,3,2,random,"{'criterion': 'gini', 'max_depth': 5, 'max_fea...",0.783083,0.785167,0.785250,0.784500,0.001002,504
257,0.022352,0.000496,0.004966,1.085927e-04,entropy,None,sqrt,1,2,random,"{'criterion': 'entropy', 'max_depth': None, 'm...",0.779500,0.778083,0.786917,0.781500,0.003874,512

In [25]:
ytrain_pred=model1.predict(xtrain)
ytest_pred=model1.predict(xtest)

In [26]:
print(classification_report(ytrain,ytrain_pred))

              precision    recall  f1-score   support

           0       0.90      0.95      0.92     28010
           1       0.77      0.64      0.70      7990

    accuracy                           0.88     36000
   macro avg       0.84      0.79      0.81     36000
weighted avg       0.87      0.88      0.87     36000

In [20]:
print(classification_report(ytest,ytest_pred))

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      6990
           1       0.70      0.59      0.64      2010

    accuracy                           0.85      9000
   macro avg       0.79      0.76      0.77      9000
weighted avg       0.84      0.85      0.85      9000

In [21]:
grid_search=GridSearchCV(
    estimator=DecisionTreeClassifier(random_state=42),
    param_grid={
        'criterion':['gini','entropy'],
        'splitter':['best','random'],
        'max_depth':[None,5,10,20],
        'min_samples_split':[2,3,5,7],
        'min_samples_leaf':[1,3,5,7],
        'max_features':['auto','sqrt','log2'] 
    },
    cv=10,
    verbose=1
)
grid_search.fit(xtrain,ytrain)

Fitting 10 folds for each of 768 candidates, totalling 7680 fits

c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
2560 fits failed out of a total of 7680.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
2560 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
  File "c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
  File "c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
c:\Users\ayyok\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.81019444 0.78933333 0.81922222 0.80333333
 0.81708333 0.80838889 0.82125    0.81186111 0.82494444 0.81147222
 0.82494444 0.81147222 0.82494444 0.81147222 0.82330556 0.81430556
 0.83263889 0.79072222 0.83263889 0.79072222 0.83263889 0.79072222
 0.83263889 0.79072222 0.83808333 0.79069444 0.83808333 0.79069444
 0.83808333 0.79069444 0.83808333 0.79069444 0.81333333 0.80044444
 0.81811111 0.80772222 0.82011111 0.81472222 0.82375    0.81713889
 0.82516667 0.82580556 0.82516667 0.82580556 0.82516667 0.82580556
 0.82905556 0.82930556 0.83566667 0.83413889 0.83566667 0.83413889
 0.83566667 0.83413889 0.83566667 0.83413889 0.83777778 0.82936111
 0.83777778 0.82936111 0.83777778 0.82936111 0.83777778 0.82936111
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.83477778 0.78625    0.83477778 0.78625
 0.83477778 0.78625    0.83477778 0.78625    0.83483333 0.78594444
 0.83483333 0.78594444 0.83483333 0.78594444 0.83483333 0.78594444
 0.83633333 0.78477778 0.83633333 0.78477778 0.83633333 0.78477778
 0.83633333 0.78477778 0.83569444 0.78477778 0.83569444 0.78477778
 0.83569444 0.78477778 0.83569444 0.78477778 0.83861111 0.79116667
 0.83861111 0.79119444 0.84011111 0.79119444 0.84011111 0.79116667
 0.84016667 0.79119444 0.84016667 0.79119444 0.84016667 0.79119444
 0.84016667 0.79119444 0.84541667 0.79663889 0.84541667 0.79663889
 0.84541667 0.79663889 0.84541667 0.79663889 0.85286111 0.79855556
 0.85286111 0.79855556 0.85286111 0.79855556 0.85286111 0.79855556
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.85086111 0.80625    0.85061111 0.80694444
 0.85013889 0.80691667 0.84966667 0.80733333 0.85122222 0.80219444
 0.85122222 0.80219444 0.85122222 0.80219444 0.85013889 0.80136111
 0.84875    0.78894444 0.84875    0.78894444 0.84875    0.78894444
 0.84875    0.78894444 0.85175    0.78925    0.85175    0.78925
 0.85175    0.78925    0.85175    0.78925    0.85533333 0.817
 0.85455556 0.81419444 0.85661111 0.82336111 0.85547222 0.81752778
 0.85427778 0.81508333 0.85427778 0.81508333 0.85427778 0.81508333
 0.85372222 0.82133333 0.85552778 0.81961111 0.85552778 0.81961111
 0.85552778 0.81961111 0.85552778 0.81961111 0.85411111 0.81163889
 0.85411111 0.81163889 0.85411111 0.81163889 0.85411111 0.81163889
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.82847222 0.81719444 0.83161111 0.81491667
 0.82911111 0.82325    0.83163889 0.82347222 0.82961111 0.81294444
 0.82961111 0.81294444 0.82961111 0.81294444 0.83086111 0.8155
 0.83822222 0.78952778 0.83822222 0.78952778 0.83822222 0.78952778
 0.83822222 0.78952778 0.83975    0.79008333 0.83975    0.79008333
 0.83975    0.79008333 0.83975    0.79008333 0.82738889 0.82272222
 0.83027778 0.83205556 0.83163889 0.83136111 0.83236111 0.83427778
 0.83325    0.83325    0.83325    0.83325    0.83325    0.83325
 0.83286111 0.8345     0.83819444 0.83263889 0.83819444 0.83263889
 0.83819444 0.83263889 0.83819444 0.83263889 0.84044444 0.83283333
 0.84044444 0.83283333 0.84044444 0.83283333 0.84044444 0.83283333
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.81327778 0.78963889 0.82380556 0.80175
 0.81991667 0.81075    0.81894444 0.81375    0.82327778 0.81577778
 0.82327778 0.81577778 0.82327778 0.81577778 0.82405556 0.81591667
 0.83083333 0.78994444 0.83083333 0.78994444 0.83083333 0.78994444
 0.83083333 0.78994444 0.8365     0.79105556 0.8365     0.79105556
 0.8365     0.79105556 0.8365     0.79105556 0.81733333 0.80138889
 0.81858333 0.80955556 0.82069444 0.81747222 0.82008333 0.81944444
 0.82366667 0.82569444 0.82366667 0.82569444 0.82366667 0.82569444
 0.82416667 0.82338889 0.82925    0.83241667 0.82925    0.83241667
 0.82925    0.83241667 0.82925    0.83241667 0.83755556 0.83291667
 0.83755556 0.83291667 0.83755556 0.83291667 0.83755556 0.83291667
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.83472222 0.78625    0.83472222 0.78625
 0.83472222 0.78625    0.83472222 0.78625    0.83433333 0.78594444
 0.83433333 0.78594444 0.83433333 0.78594444 0.83483333 0.78594444
 0.83511111 0.78477778 0.83511111 0.78477778 0.83511111 0.78477778
 0.83511111 0.78477778 0.83541667 0.78477778 0.83541667 0.78477778
 0.83541667 0.78477778 0.83541667 0.78477778 0.84255556 0.79027778
 0.84255556 0.79027778 0.84255556 0.79022222 0.84255556 0.79022222
 0.84255556 0.79019444 0.84255556 0.79019444 0.84255556 0.79019444
 0.84255556 0.79019444 0.84261111 0.79938889 0.84261111 0.79938889
 0.84261111 0.79938889 0.84261111 0.79938889 0.84261111 0.79647222
 0.84261111 0.79647222 0.84261111 0.79647222 0.84261111 0.79647222
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.85016667 0.80569444 0.85038889 0.80480556
 0.85180556 0.80475    0.85066667 0.80725    0.84958333 0.80047222
 0.84958333 0.80047222 0.84958333 0.80047222 0.85227778 0.79986111
 0.84627778 0.78830556 0.84627778 0.78830556 0.84627778 0.78830556
 0.84627778 0.78830556 0.84725    0.78855556 0.84725    0.78855556
 0.84725    0.78855556 0.84725    0.78855556 0.85616667 0.82344444
 0.85297222 0.81638889 0.85433333 0.81816667 0.85341667 0.81716667
 0.85372222 0.81530556 0.85372222 0.81530556 0.85372222 0.81530556
 0.85405556 0.82205556 0.85355556 0.81352778 0.85355556 0.81352778
 0.85355556 0.81352778 0.85355556 0.81352778 0.85194444 0.81697222
 0.85194444 0.81697222 0.85194444 0.81697222 0.85194444 0.81697222
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.83094444 0.81744444 0.83091667 0.81880556
 0.83044444 0.82063889 0.82966667 0.81902778 0.83119444 0.80944444
 0.83119444 0.80944444 0.83119444 0.80944444 0.83111111 0.81213889
 0.8355     0.78944444 0.8355     0.78944444 0.8355     0.78944444
 0.8355     0.78944444 0.83738889 0.789      0.83738889 0.789
 0.83738889 0.789      0.83738889 0.789      0.82891667 0.82902778
 0.83236111 0.82833333 0.83108333 0.83163889 0.83172222 0.83375
 0.83163889 0.83191667 0.83163889 0.83191667 0.83163889 0.83191667
 0.835      0.83477778 0.83719444 0.83427778 0.83719444 0.83427778
 0.83719444 0.83427778 0.83719444 0.83427778 0.84008333 0.83630556
 0.84008333 0.83630556 0.84008333 0.83630556 0.84008333 0.83630556]
  warnings.warn(

GridSearchCV(cv=10, estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [None, 5, 10, 20],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 3, 5, 7],
                         'min_samples_split': [2, 3, 5, 7],
                         'splitter': ['best', 'random']},
             verbose=1)

In [ ]:
model2=grid_search.best_estimator_
model2.fit(xtrain,ytrain)

In [ ]:
ytrain_pred=model2.predict(xtrain)
ytest_pred=model2.predict(xtest)

In [22]:
print(classification_report(ytrain,ytrain_pred))
print(classification_report(ytest,ytest_pred))

              precision    recall  f1-score   support

           0       0.90      0.95      0.92     28010
           1       0.77      0.64      0.70      7990

    accuracy                           0.88     36000
   macro avg       0.84      0.79      0.81     36000
weighted avg       0.87      0.88      0.87     36000

              precision    recall  f1-score   support

           0       0.89      0.93      0.91      6990
           1       0.70      0.59      0.64      2010

    accuracy                           0.85      9000
   macro avg       0.79      0.76      0.77      9000
weighted avg       0.84      0.85      0.85      9000

In [28]:
import os

In [ ]:
print(os.cpu_count()) #12 cpu core #n_jobs=1 => 1 cpu core #n_jobs=2 =>2 cpu core #n_jobs=-1 => all cpu core

12