In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder,TargetEncoder

In [2]:
d={
    'col1':['A','B','B','D','B','A','C','C','A','A'],
    'col2':['S1','S2','S3','S3','S1','S3','S2','S2','S1','S3'],
    'col3':['M1','M2','M3','M2','M3','M2','M1','M3','M1','M2'],
    'col4':[10,30,20,40,10,30,50,20,30,60]
}

In [3]:
df=pd.DataFrame(d)
df

  col1 col2 col3  col4
0    A   S1   M1    10
1    B   S2   M2    30
2    B   S3   M3    20
3    D   S3   M2    40
4    B   S1   M3    10
5    A   S3   M2    30
6    C   S2   M1    50
7    C   S2   M3    20
8    A   S1   M1    30
9    A   S3   M2    60

In [4]:
# sns.scatterplot(df,x='col1',y='col4')

In [5]:
x=df.drop(columns='col4')
y=df['col4']

In [6]:
print(x)

  col1 col2 col3
0    A   S1   M1
1    B   S2   M2
2    B   S3   M3
3    D   S3   M2
4    B   S1   M3
5    A   S3   M2
6    C   S2   M1
7    C   S2   M3
8    A   S1   M1
9    A   S3   M2

In [7]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,train_size=0.8,random_state=42)

In [8]:
xtrain

  col1 col2 col3
5    A   S3   M2
0    A   S1   M1
7    C   S2   M3
2    B   S3   M3
9    A   S3   M2
4    B   S1   M3
3    D   S3   M2
6    C   S2   M1

In [9]:
xtest

  col1 col2 col3
8    A   S1   M1
1    B   S2   M2

In [10]:
encoding = OrdinalEncoder(categories=[['A','B','C'], ['S1','S2','S3']],handle_unknown='use_encoded_value',unknown_value=-1)
encoding.fit_transform(xtrain[['col1', 'col2']])

array([[ 0.,  2.],
       [ 0.,  0.],
       [ 2.,  1.],
       [ 1.,  2.],
       [ 0.,  2.],
       [ 1.,  0.],
       [-1.,  2.],
       [ 2.,  1.]])